baseurl = "https://sldn.softlayer.com/"
languageCode = "en-us"
title = "SoftLayer API"
canonifyurls = true
SectionPagesMenu = "sections"
pygmentsUseClasses=true
pluralizelisttitles = "false"
paginate = 10
googleAnalytics = "G-9XPZ9ZBSJE"
disablePathToLower = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = '#'

[params]
  description = "SoftLayer API Examples, implementations, and release notes."
  author = "SoftLayer"

[taxonomies]
	tag = "tags"
	class = "classes"

pluralizeListTitles = false

[[menu.main]]
    name = "Documentation"
    identifier = "sldn"
    url = "/reference/softlayerapi"
[[menu.main]]
    name = "Articles"
    identifier = "article"
    url ="/article/"
[[menu.main]]
    name = "Go"
    identifier = "go"
    url = "/go/"
[[menu.main]]
    name = "Perl"
    identifier = "perl"
    url = "/perl/"
[[menu.main]]
    name = "Java"
    identifier = "java"
    url = "/java/"
[[menu.main]]
    name = "Python"
    identifier = "python"
    url = "/python/"
[[menu.main]]
    name = "Ruby"
    identifier = "ruby"
    url = "/ruby/"
[[menu.main]]
	name = "Rest"
	identifier = "rest"
	url = "/rest/"
[[menu.main]]
    name = "PHP"
    identifier = "php"
    url = "/php/"
[[menu.main]]
    name = "Tools"
    identifier = "tools"
    url = "/tools/"

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]
  taxonomyTerm = ["HTML"]
  taxonomy = ["HTML"]


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      # required to allow for raw HTML in reference files
      unsafe = true 
      xHTML = false
